abstract_factory:
    resource: "@AbstractFactoryBundle/Controller/"
    type:     annotation
    prefix:   /abstract-factory

observer:
    resource: "@ObserverBundle/Controller/"
    type:     annotation
    prefix:   /observero

factory_method:
    resource: "@FactoryMethodBundle/Controller/"
    type:     annotation
    prefix:   /factory-method

simple_factory:
    resource: "@SimpleFactoryBundle/Controller/"
    type:     annotation
    prefix:   /simple-factory

strategy:
    resource: "@StrategyBundle/Controller/"
    type:     annotation
    prefix:   /strategy

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
